### ISSUE TITLE
Move all comments from cpp to headers

### ISSUE THREAD

**Issue by gyurgyma** [AgreeableDeerGames/GameBackbone#239]
**Is your feature request related to a problem? Please describe.**
Having our documentation in cpps was always bad, but with more and more templates, the documentation is split between headers and cpps.

**Describe the solution you'd like**
All documentation should be moved to headers.

**Comment by lavinrp** [comment]
When we do this it would also be nice to switch to Doxygen style comments instead of XML comments.

Its more common in C++ and much less verbose

**Comment by lavinrp** [comment]
feature/i239-header_comments has updated our comment style for everything but CompoundSprite (I didn't want to have a huge merge conflict with Chris's changes). It currently depends on https://github.com/AgreeableDeerGames/GameBackbone/pull/254 (also because I didn't want to have a huge merge conflict).

**Comment by lavinrp** [comment]
Closed with https://github.com/AgreeableDeerGames/GameBackbone/pull/257
